"""Apply the user-authorized review fixes to the existing manuscript, once.

Inputs/results are untouched. Later fixes must edit the same source incrementally.
"""
from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(Path(__file__).parent))
import build_full_paper_figures as draw
import revise_full_paper_presentation as presentation

MARKER='% FULL_SKILL_AUDIT_20261007'

# These explanations are intentionally self-contained: scope, construction,
# numerical result and interpretation, using the skill's 100--150 token rule.
CAPTIONS={
'tab:terms':r'''Symbols used throughout the planning model. Reporting regions aggregate results, inspection units carry local tasks, and months index seasonal work. Areas generate check demand, while normalized weights express responsibility rather than incident probabilities. Completion is credited only where a ground team meets the response deadline. Personnel-hours and flight-hours are separate resources: operating a drone also consumes personnel work. The baseline provides 21240 personnel-hours and 1200 flight-hours monthly, with 2880 personnel-hours reserved once for response readiness. These definitions prevent adding incompatible units or counting response crews separately for every inspection. The reported rate is weighted checklist completion with response support, rather than the fraction of animals surviving or land continuously observed.''',
'tab:priorities':r'''Provisional conservation priorities for the Etosha planning case. The ranking uses the supplied threat context, possible losses and opportunities for intervention, rather than measured incident probabilities. Illegal entry and poaching create animal-monitoring and response tasks; harmful fire and habitat disturbance create a separate habitat-monitoring component. Six animal groups with usable 2015 survey records support regional responsibility estimates, while rhinoceros poaching remains a qualitative concern because its count table is unresolved. Grassland, shrubland and forest identify burnable habitat. Disease, human--wildlife conflict and missing priority species require dedicated evidence and safeguards. The two ranked concerns organize the quantified task list without claiming an exhaustive risk inventory or equal vulnerability across species.''',
'tab:parameters':r'''Declared operating assumptions used to construct the Etosha allocation problem. Travel speeds convert mapped routes into task costs and response eligibility; checklist, endurance and openness rules determine feasible monitoring technologies. Each region receives a service floor proportional to its reachable area. A reference workforce of 295 with 60\% availability and 120 effective hours supplies 21240 personnel-hours monthly. Thirty proposed drones supply 1200 flight-hours. Six candidate response posts reserve 2880 personnel-hours in total. These settings describe a planning protocol, not verified park staffing, equipment or operating permissions. Sensitivity cases change individual assumptions while retaining the others, so budget shortages can be distinguished from geographic or technological restrictions.''',
'fig:etosha':r'''Regional responsibility and base area service in Etosha. The first panel uses six historical animal groups, legal-category preference weights, burnable habitat and an entry-access proxy to construct normalized demand. The second panel aggregates optimized completion by area, using the same 599 inspection units and the two-hour ground-response rule. Stars locate the six assumed response posts; red points identify units that fail that rule. Eligible units cover 34.12\% of projected park area, while their priority-weighted completion is 57.26\%. The distinction explains why the two panels cannot share a scoring interpretation. Unsurveyed animal values remain unknown, and neither regional shading nor representative-point checks establish continuous observation or measured ecological protection.''',
'fig:costs':r'''Personnel work required for one checklist inspection at ENP1\_0000. Costs are calculated from the saved route, off-road distance, two-person crews, preparation and observation times. A ground inspection requires 4.981 personnel-hours; the drone-assisted alternative requires 4.271 personnel-hours and separately consumes 0.206 flight-hours. Both retain road transport and human involvement. The colored segments distinguish road travel, off-road walking, observation or flight, and preparation, making the assumed substitution explicit. Savings arise from replacing slow off-road walking in a technically suitable location, not from removing operators or responders. These quantities are modeled per-check costs rather than observed patrol durations, and checklist equivalence must be tested before operational deployment.''',
'tab:regions':r'''Regional demand and the minimum-labor allocation at the optimal Etosha rate. Demand uses conservation-priority weights, whereas reach and service are area-weighted fractions within each reporting region. Labor includes ground screening and drone support, and excludes the shared 2880 readiness hours. The global second stage preserves the 57.26\% optimum while allowing all completion fractions to change. ENP1 receives 487.89 monitoring-support hours and ENP12 receives 385.64; ENP9 receives no credited service because no unit qualifies for timely response. The salt pan retains its regional service floor despite a zero measured-component weight. Unknown animal values are not imputed zeros, and monthly regional totals do not specify integer employees or aircraft stationed locally.''',
'fig:deployment':r'''Spatial distribution of the minimum-labor optimal-rate allocation across all 17 reporting regions. Panel (a) maps monitoring and drone-support personnel work; panel (b) maps drone flight-hours. Each scale is independently normalized, so matching colors across panels do not imply equal resource quantities. Numeric labels identify ENP regions, including the combined 3410 unit; P denotes the main pan and O denotes survey-external areas. Leaders identify displaced labels. ENP1 has the largest allocations, 487.89 personnel-hours and 29.31 flight-hours. Six stars mark assumed response posts, each reserving 480 personnel-hours outside regional shading. The maps show pooled monthly workloads under fixed sites, rather than aircraft locations, continuous coverage or measured ecological outcomes.''',
'tab:comparison':r'''Completion rates for three allocation rules under identical tasks, weights, response gates and resource constraints. Uniform service equalizes completion among eligible units; demand-based service follows regional demand density; optimization chooses completion and technologies jointly. All three achieve the 57.26\% geographic ceiling at the 21240-hour baseline and after a 40\% labor reduction. A separate 3600-hour stress budget includes 2880 readiness hours and retains 1200 flight-hours. Its rates are 16.47\%, 19.87\% and 29.88\%, respectively. The contrast identifies an optimization advantage under scarcity without inventing a baseline improvement. Each plan satisfies the same regional floors, and the comparison concerns checklist service rather than observed incident reduction or animal survival.''',
'tab:forward':r'''Additional response-post candidates tested within the original total resource budgets. Each candidate adds 480 readiness personnel-hours, and routes, response eligibility and inspection costs are rebuilt while evaluation weights remain fixed. The original six-post configuration achieves 57.26\% using 5286.11 personnel-hours. Adding the ENP5 candidate achieves 64.27\% using 6202.08 personnel-hours, a 7.01 percentage-point gain. The other two candidates provide smaller rate gains with different workload requirements. This enumeration isolates the effect of response access rather than increasing the overall labor allowance. ENP5 is best among three tested locations, not a globally optimized station network. Mapped access, permissions, incident concurrency and facilities require verification before a site recommendation becomes operational.''',
'tab:season':r'''Medium seasonal service rules for the monthly workforce model. The cited seasonal classifications establish the operating windows, while numerical visit frequencies and extra checklist requirements are team planning assumptions. Regular maintenance visits occur twice per point in wet months and four times in dry months. Extra fire screening increases from zero to two and then four checks per 100 square kilometers of burnable habitat. November combines wet maintenance with the late-fire rule. Each month represents 30 planning days, and each available worker supplies 120 effective hours. These additional tasks share the baseline personnel and flight resources; they do not redefine the basic inspection score or predict animal abundance, rainfall, fire occurrence or water-delivery volumes.''',
'tab:water':r'''Maintenance workloads for the 17 boreholes documented in the historical field sample. Every modeled visit uses a two-person crew, a directed round trip, five minutes of preparation and the specified on-site work. Summed elapsed round-trip travel is 42.87565 hours. Two regular visits produce 211.17 personnel-hours monthly; four produce 422.34. The drought-maintenance scenario assumes eight visits and one on-site hour, producing 980.68 personnel-hours. These differences result from service rules rather than measured faults or inferred water shortages. Independent round trips claim no combined-route savings. The sample is not a complete inventory of currently functioning facilities, and drones cannot replace physical equipment maintenance, major repairs or unmeasured emergency work.''',
'fig:workflow':r'''Overall organization of the protection-planning study. The lower layer distinguishes supplied reference values, historical surveys and mapped geography from operating assumptions. The task layer converts animal and habitat responsibility into checklist demand and response eligibility. The solution layer links the maximum-rate allocation to inverse seasonal workforce calculations and local park adaptations. Independent checks then evaluate capacity, units, budgets, service floors and sensitivity, before recommendations are interpreted as conditional workload estimates. For Etosha, the linked calculations give a 57.26\% baseline rate and normal and drought-maintenance peaks of 57 and 62 personnel equivalents. Upward arrows represent dependencies, not causal ecological effects or a claim that every input has been field calibrated.''',
'fig:monthly':r'''Minimum monthly work required to preserve the 57.26\% baseline inspection target under the medium seasonal rules. The stacked bars separate shared response readiness, basic inspection support, extra fire checks and maintenance of 17 historical boreholes. August through October are the busiest months at 6831.83 personnel-hours, requiring 57 available personnel equivalents after division by 120 and upward rounding. The reference capacity of 177 personnel is outside the plotted workload scale. Seasonal increases use spare modeled resources while the response-limited baseline score remains unchanged. These pooled monthly quantities explain strategic workforce needs; they do not certify an executable daily roster, personnel qualifications, simultaneous alert coverage or the completeness of the park's real task inventory.''',
'tab:monthly':r'''Minimum work and personnel equivalents for the four medium-rule seasonal periods. Each row preserves the same unrounded 57.26016128 baseline target and uses the shared 1200 flight-hour allowance. January through April and December require 5497.28 personnel-hours and 46 equivalents. May through July require 53; August through October require 57; November requires 56. Flight work peaks at 210.61 hours. Fixed reference availability of 177 personnel maintains the target in all periods because its capacity exceeds the included workload. The annual fixed team is the maximum monthly requirement rather than the sum of monthly headcounts. These estimates retain the existing response range and assumed checklist, so omitted specialist, night or concurrent incident work may change actual staffing needs.''',
'tab:standards':r'''Workforce requirements under low, medium and high assumed seasonal service rules. The alternatives change maintenance visits and extra fire screening together, and each is solved for the same baseline inspection target. Normal peak personnel equivalents are 51, 57 and 71; the specified drought-maintenance rules raise them to 53, 62 and 77. Corresponding personnel-hours include readiness, screening support and physical maintenance rather than flight time alone. The table therefore measures the consequence of prescribed work, not a statistical confidence interval or a forecast of future drought. A lower required headcount under a relaxed checklist cannot be called unchanged ecological protection at lower cost. Selecting an operational rule requires task-duration, maintenance-status and outcome evidence.''',
'fig:joint':r'''Peak-month effective inspection completion under joint personnel and drone-flight limits. Each cell is independently reoptimized for the medium seasonal workload, including mandatory maintenance and extra fire screening. Rows specify available personnel at 120 effective hours each, and columns specify monthly flight-hours. A 57-person team with 200 flight-hours maintains the 57.26\% target, whereas the same team with 160 hours reaches 56.97\%. With no drone capacity, maintaining the target requires 67 people. This interaction prevents extrapolating one-resource tests into a joint shortage. Cell values describe the stated model and response layout; they are not detection probabilities, confidence limits, a real roster or a claim that all proposed aircraft can fly simultaneously.''',
'tab:protocol':r'''Sensitivity of technology choice to assumed inspection protocols under the unchanged baseline budgets. Drone efficiency scales completed checklist capacity relative to the baseline, and a ground minimum requires an explicit share of completed checks to use ground screening. All tested protocols retain the 57.26\% geographic ceiling, but workloads change. At 75\% drone efficiency, ground screening returns at 1731.55 personnel-hours and total labor becomes 5786.37. A 25\% ground requirement uses 801.56 ground hours and 5486.15 total hours. These are separate assumption tests, not measured detection rates. The results show that zero baseline ground screening depends on checklist equivalence and ample resources; operators, readiness and task-specific physical interventions remain necessary.''',
'tab:grid':r'''Spatial discretization sensitivity with task density, resource budgets and response rules held fixed. The 5, 10 and 15 kilometer grids produce 1554, 599 and 392 connected inspection units, respectively. Their completion rates are 56.39\%, 57.26\% and 59.99\%, and minimum personnel work is 5279.44, 5286.11 and 5340.08 hours. Total prescribed checks remain proportional to park area, so grid refinement does not create extra aggregate demand. Representative locations and response qualification change, particularly near the two-hour boundary. The finer result is 0.87 percentage points below the baseline and the coarser result is 2.73 above it. These differences measure approximation sensitivity rather than sampling uncertainty or a statistical confidence interval.''',
'tab:weights':r'''Responsibility-weight sensitivity and evaluation using a common reference rule. Entropy, equal components, animal emphasis and CRITIC assign different animal--habitat shares while preserving routes, budgets and checklist requirements. The own-weight column scores each optimized plan under its chosen rule; original-weight evaluation applies the baseline entropy rule to all plans. At the ample baseline, deployment is identical and original-weight completion remains 57.26\%, despite changes in the scoring scale. The tight-budget column uses original weights and the separate 3600-hour labor constraint; results span 29.86\% to 29.88\%. This paired evaluation prevents a changed definition of importance from masquerading as improved service. Weight choices remain management scenarios rather than measured ecological loss shares.''',
'tab:limits':r'''Limits that affect operational interpretation of the protection-planning model. Historical and incomplete object records restrict whose responsibility can be quantified; checklist and cost assumptions restrict the meaning of service completion. Mapped roads do not establish legal or seasonal permissions, and pooled monthly hours do not ensure qualified crews at every time. The 17-point maintenance sample cannot identify all current facilities or repair tasks. These limits explain why the computed 57.26\% optimum and 57 or 62 personnel equivalents cannot certify sufficient ecological protection or actual park staffing. The final column identifies corresponding evidence needs. Independent mathematical checks address feasibility of the specified model, while incident, survey, habitat and field-work records are needed to validate real outcomes.''',
'fig:transfer':r'''Published geographic inputs and candidate response locations for the two cross-continent trials. Chitwan uses a public protected-area polygon, mapped roads and named geographic anchors; Yellowstone uses the NPS boundary, public roads and station locations. Stars identify the baseline candidates and the additional candidate, rather than verified staffing assignments. Terrain-specific metric projections support travel calculations, while local speeds, task times and permissions remain assumptions. Chitwan's projected polygon covers 1214.06 square kilometers, exceeding the official 952.63 by 27.44\%, so its trial remains uncalibrated. Yellowstone's mapped inputs support a local terrestrial-service calculation. Neither panel transfers Etosha species weights, assumes its thirty-drone fleet, or establishes continuous monitoring, current animal distributions or actual staffing requirements.''',
'tab:transferdata':r'''Spatial inputs for the terrestrial-service trials in Chitwan and Yellowstone. Land service areas exclude sampled permanent water, and forest shares come from WorldCover 2021 classification sampled at 100 meters. Mapped road lengths and connected planning cells support local route and response calculations. The Chitwan polygon supplies 1175.65 square kilometers of land service area and 1376 one-kilometer cells; the Yellowstone NPS boundary supplies 8470.07 and 1520 cells of 2.5 kilometers. These data rebuild local geography rather than calibrate animal protection. Chitwan's boundary-area inconsistency remains explicit. Different areas and grids make park scores local task measures, so the table cannot rank ecological condition or justify transferring a personnel total between parks.''',
'tab:transfercases':r'''Conditional land-inspection trials under local geography and declared operating rules. Each park's target is fixed at 90\% of its own two-post, 30 kilometer-per-hour response ceiling, rather than 90\% of the whole park. Baseline Chitwan and Yellowstone require 1085.15 and 1541.63 personnel-hours, or 10 and 13 task equivalents. At 20 kilometers per hour, both fixed targets exceed the resulting geographic ceilings and are infeasible. Adding a third post expands response eligibility but adds 480 readiness hours, increasing work at the original target. Higher speeds are sensitivity assumptions rather than driving recommendations. Chitwan remains a public-polygon trial, and neither park's result includes unmeasured community, visitor, specialist or concurrent incident tasks.''',
'tab:wolf':r'''Yellowstone historical-priority scenarios with unchanged roads, costs and checklist tasks. Ten published 2022 wolf-pack activity files contain nine distinct geometries; their clipped union covers 4093.87 square kilometers. Historical overlap is adjusted by existing cell land fraction and mixed with land-area responsibility using the assumed wolf share. Each scenario retains the original Y0 plan's score under its new weights, then minimizes personnel work. At a 50\% historical share, 61 units change service and work falls to 1474.68 hours, while original land-weight completion falls from 16.85\% to 15.12\%. This is a priority trade-off, not improved ecological protection. Historical activity extents are not current density, measured threat or official management weights.'''
}

def main():
    p=ROOT/'docs/paper/full_paper.tex';tex=p.read_text(encoding='utf-8')
    assert MARKER not in tex,'Apply once; edit the same source incrementally afterward.'
    # Full paper remains the same self-contained source and editor document.
    tex=tex.replace('headheight=12bp','headheight=15bp').replace(r'\fontsize{9}{10.8}',r'\fontsize{12}{14.4}').replace(r'\fontsize{10}{12}',r'\fontsize{12}{14.4}').replace(r'\fontsize{11}{13.2}',r'\fontsize{12}{14.4}')
    tex=tex.replace('justification=centering','justification=justified,singlelinecheck=false')
    tex=tex.replace(r'\usepackage{needspace}',r'\usepackage{needspace,placeins}')
    for env in ['figure','table']:
        tex=re.sub(r'\\begin\{'+env+r'\}\[[^]]+\]',r'\\begin{'+env+'}[H]',tex)
    # Refresh the complete regional map with all identifiers.
    presentation.allocation_map(draw.read('output/question2/q2_model_inputs.json'),draw.read('output/question2/q2_results.json'))
    pattern=r'\\begin\{figure\}.*?\\label\{fig:deployment\}.*?\\end\{figure\}'
    match=next(m for m in re.finditer(r'\\begin\{figure\}.*?\\end\{figure\}',tex,re.S) if r'\label{fig:deployment}' in m[0])
    new=match[0];a=new.index(r'\begin{tikzpicture}');b=new.index(r'\end{tikzpicture}')+len(r'\end{tikzpicture}')
    new=new[:a]+(ROOT/'output/full_paper/figures/fig7_optimal_resource_deployment.tikz').read_text(encoding='utf-8').strip()+new[b:]
    tex=tex[:match.start()]+new+tex[match.end():]
    for key,caption in CAPTIONS.items():
        tokens=re.findall(r'[A-Za-z0-9]+(?:[.,][0-9]+)*',re.sub(r'\\[A-Za-z]+',' ',caption))
        assert 100<=len(tokens)<=150,(key,len(tokens))
        found=next(m for m in re.finditer(r'\\begin\{(?:figure|table)\}.*?\\end\{(?:figure|table)\}',tex,re.S) if '\\label{'+key+'}' in m[0])
        fragment=found[0];fragment,n=re.subn(r'\\caption\{[^\n]+\}',lambda _:r'\caption{'+caption+'}',fragment)
        assert n==1,key;tex=tex[:found.start()]+fragment+tex[found.end():]
    # Source paragraph boundaries are meaningful after every display/float.
    tex=re.sub(r'(\\end\{(?:equation|figure|table)\})\n(?!\n)',r'\1\n\n',tex)
    # Do not force an almost empty page at every major section.
    tex=tex.replace('\n\\clearpage\n\\section{','\n\\FloatBarrier\n\\section{')
    tex=tex.replace(r'\flushbottom',r'\raggedbottom')
    # One layered overall architecture, using the bundled architecture skill's
    # band/head/white-component recipe and unchanged readable 12pt type.
    c=draw.Canvas(16.8,5.0)
    layers=[('Evidence','Survey, law, land cover','Roads, posts, protocols','#56B4E9'),
            ('Tasks','Responsibility and checks','Route costs and response','#0072B2'),
            ('Solutions','Maximum rate; least work','Seasonal and local variants','#009E73'),
            ('Verification','Independent constraints','Protocol, grid and weights','#E69F00'),
            ('Planning','Monthly staff equivalents','Field tests and local plans','#CC79A7')]
    for i,(head,left,right,color) in enumerate(layers):
        y=.15+i*.98
        from matplotlib import colors
        rgb=colors.to_rgb(color);pale=colors.to_hex(tuple(.92+.08*x for x in rgb))
        c.rect(.2,y,16.4,.72,pale,color,.45)
        c.rect(.35,y+.08,2.65,.56,pale,color,.45)
        c.rect(3.3,y+.08,6.25,.56,'white','#9aa5ac',.4)
        c.rect(9.95,y+.08,6.25,.56,'white','#9aa5ac',.4)
        c.text(1.675,y+.36,head,bold=True)
        c.text(6.425,y+.36,left)
        c.text(13.075,y+.36,right)
        if i<4:c.line([(8.4,y+.74),(8.4,y+.96)],draw.GREY,.65,arrow=True)
    c.save('Q0_overall_planning_architecture')
    workflow=next(m for m in re.finditer(r'\\begin\{figure\}.*?\\end\{figure\}',tex,re.S) if r'\label{fig:workflow}' in m[0])
    tex=tex[:workflow.start()]+tex[workflow.end():]
    architecture='\n'.join([r'\begin{figure}[H]',r'\centering',(ROOT/'output/full_paper/figures/Q0_overall_planning_architecture.tikz').read_text(encoding='utf-8').strip(),r'\caption{'+CAPTIONS['fig:workflow']+'}',r'\label{fig:workflow}',r'\end{figure}',''])
    # Shorten repeated introduction details; methods and assumptions remain below.
    a=tex.index(r'\section{Introduction}');b=tex.index(r'\section{Basic Assumptions',a)
    intro=r'''\section{Introduction}
Large wildlife reserves face a practical protection problem: important locations are spread across a wide area, while personnel, equipment and travel time are limited. Observations are useful only when qualified teams can act on them. Etosha National Park is the starting case, with a reported area of about 22,935 km$^2$ and 295 reference employees \cite{problem}. We ask how to prioritize inspections, allocate ground and drone work, and maintain a chosen service as seasonal tasks increase.

Our planning units connect historical animal responsibility, burnable habitat and mapped access to explicit checklist demand. A task receives service credit when its prescribed screening is completed and ground staff can arrive within two hours. The resulting Effective Inspection Completion Rate summarizes weighted tasks, rather than wildlife survival or continuous area coverage. Six surveyed animal groups support the quantitative component; missing species and current distributions remain separate evidence needs.

A two-stage linear program maximizes this rate and then minimizes personnel work among equally optimal allocations. A monthly extension maintains the same target while adding fire screening and maintenance of 17 historical boreholes. Inverse workload divided by 120 effective hours gives personnel equivalents. Joint resource, protocol, grid and weight tests examine the assumptions. Trials in Chitwan and Yellowstone rebuild local geography and priorities instead of transferring Etosha's staffing totals.

The baseline rate is 57.26\%, using 5286.11 personnel-hours and 144.34 flight-hours. Existing response access limits this result despite spare resources. Normal seasonal work requires 57 personnel equivalents at its peak; the specified drought-maintenance rule requires 62. These are conditional task estimates. Figure~\ref{fig:workflow} organizes the study's data, models, checks and recommendations, showing where numerical verification ends and field calibration remains necessary.

\FloatBarrier
'''
    intro=intro.replace(r'\FloatBarrier',architecture+'\n'+r'\FloatBarrier')
    tex=tex[:a]+intro+tex[b:]
    tex=tex.replace(MARKER,'')
    tex=tex.replace(r'\begin{document}',MARKER+'\n'+r'\begin{document}',1)
    p.write_text(tex,encoding='utf-8',newline='\n')
    zh=ROOT/'docs/paper/full_paper_zh.tex';s=zh.read_text(encoding='utf-8').replace('headheight=12bp','headheight=15bp').replace(r'\fontsize{9}{10.8}',r'\fontsize{12}{14.4}').replace(r'\fontsize{10}{12}',r'\fontsize{12}{14.4}').replace(r'\fontsize{11}{13.2}',r'\fontsize{12}{14.4}')
    zh.write_text(s,encoding='utf-8',newline='\n')
    (ROOT/'output/full_paper/skill_audit_20261007/caption_inventory.json').write_text(json.dumps({k:{'text':v,'tokens':len(re.findall(r'[A-Za-z0-9]+(?:[.,][0-9]+)*',re.sub(r'\\[A-Za-z]+',' ',v)))} for k,v in CAPTIONS.items()},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print('Existing full manuscript updated; 24 standalone explanations and all-region labels applied.')

if __name__=='__main__':main()
