name: himcn-roads
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - requests
      - beautifulsoup4
      - osmium
      - shapely
      - pyproj
      - networkx
      - pandas
      - matplotlib
      - geopandas
      - pyogrio
      - duckdb
